/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

import { Platform } from "react-native";

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    primary: '#000',
    headerBackground: '#912828ff',
    headerText: '#ffffff',
    navbarBackground: '#ffffff',
    active: '#3b82f6',
    inactive: '#919191ff',
    text: '#000000ff',
    subtext: '#000000',
    background: '#e4e4e7',
    inputPlaceholder: '#9ca3af',
    inputBackground: '#ffffff',
    inputBorder: '#e5e7eb',
    shadowColor: '#000000',
    buttonBackground: '#3b82f6',
    buttonText: '#ffffff',
    cardBackground: '#ffffff',
    imageBorder: '#3b82f6',
    imageOverlayBackground: 'rgba(0, 0, 0, 0.4)',
    imageOverlayText: '#ffffff',
    linearGradient: Platform.OS === 'ios' ? 'rgba(228,228,231,0.1)' : 'rgba(228,228,231,0.9)',
    sectionTitle: '#000000',
    cardTitle: '#000000',
    legendText: '#000000',
    avgText: '#3b82f6',
    avgLabel: '#6b7280',
    tint: tintColorLight,
    icon: '#6b7280',
    tabIconDefault: '#9ca3af',
    tabIconSelected: tintColorLight,
    chartRed: '#ef4444',
    chartGreen: '#007a2dff',
    chartBlue: '#3b82f6',
    chartAxis: '#000',
    chartText: '#000',
    success: '#10b981',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',
  },
  dark: {
    primary: '#000',
    headerBackground: '#912828ff',
    headerText: '#f7f7f7ff',
    navbarBackground: '#1e1e1eff',
    active: '#93C5FD',
    inactive: '#fafafaff',
    text: '#ffffffff',
    subtext: '#ffffffff',
    background: '#000000ff',
    inputPlaceholder: '#c3c3c3ff',
    inputBackground: '#292929ff',
    inputBorder: '#67686cff',
    shadowColor: '#ffffffff',
    buttonBackground: '#93C5FD',
    buttonText: '#000000ff',
    cardBackground: '#1e1e1eff',
    imageBorder: '#62abebff',
    imageOverlayBackground: 'rgba(255, 254, 254, 0.4)',
    imageOverlayText: '#000000ff',
    linearGradient: 'rgba(0,0,0,0.6)',
    sectionTitle: '#ffffffff',
    cardTitle: '#ffffffff',
    legendText: '#ffffffff',
    avgText: '#93C5FD',
    avgLabel: '#afb3bcff',
    tint: tintColorDark,
    icon: '#ffffffff',
    tabIconDefault: '#9ca3af',
    tabIconSelected: tintColorDark,
    chartRed: '#EF4444',
    chartGreen: '#73f2a2ff',
    chartBlue: '#93C5FD',
    chartAxis: '#e0e0e0ff',
    chartText: '#e0e0e0ff',
    success: '#10b981',
    warning: '#f59e0b',
    error: '#EF4444',
    info: '#93C5FD',
  },
};
